tomcat:
    image: tomcat:7
    links:
        - mysql:mysql
    ports:
        - 8080:8080
    volumes:
        - ./Servers/Apache Tomcat v7.0 (2) at localhost-config/context.xml:/usr/local/tomcat/conf/context.xml:ro
        - ./Servers/Apache Tomcat v7.0 (2) at localhost-config/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
        
 mysql:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: customers
