tomcat:
    image: tomcat:7
    links:
        - mysql:mysql
    ports:
        - 8080:8080
 mysql:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: customers
